version: '3'


services:
 spring_server:
  image: chat
  build: .
  ports:
   - "1818:1818"
  environment:
   - DATABASE_HOST=db_mysql,DATABASE_USER=root,DATABASE_PASSWORD=password,DATABASE_NAME=chat,DATABASE_PORT=3307
  depends_on:
   - db_mysql
  volumes:
   - .:/chat

 db_mysql:
  image: mysql:5.7.21
  environment:
   - MYSQL_USER=root
   - MYSQL_PASSWORD=password
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_DATABASE=chat
  ports:
   - "3307:3306"
  volumes:
   - db_mysql:/var/lib/mysql
volumes:
 db_mysql:

